name: build
on:
  push:
    branches:
      - alpha
      - beta
      - development
      - master
      - lineageondemand
      - staging

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: './Dockerfile'
          hide-progress: false
          template: '@/contrib/gitlab.tpl'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM'
  
